# Generated by Django 3.0.1 on 2020-03-21 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20200308_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='courses',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 509244), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 509215), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 509176), max_length=255, primary_key=True, serialize=False),
        ),
    ]
