# Generated by Django 3.0.1 on 2020-03-21 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20200321_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='courses',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 19, 25, 48, 907654), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 19, 25, 48, 907625), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 19, 25, 48, 907584), max_length=255, primary_key=True, serialize=False),
        ),
    ]
