# Generated by Django 3.0.1 on 2020-03-22 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200322_1723'),
        ('careers', '0006_auto_20200321_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='courses',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 23, 12, 504177), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 23, 12, 504103), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 23, 12, 504000), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CareerCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Careers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
            ],
        ),
    ]
