# Generated by Django 3.0.1 on 2020-03-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_auto_20200322_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerCourses',
        ),
        migrations.DeleteModel(
            name='Careers',
        ),
    ]
