# Generated by Django 3.0.1 on 2020-03-28 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('articleId', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 700176), max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
