# Generated by Django 3.0.1 on 2020-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('articlePicture', models.BinaryField()),
                ('body', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('datePosted', models.DateTimeField()),
                ('author', models.CharField(max_length=255)),
                ('articleId', models.CharField(max_length=255, unique=True)),
                ('articleLink', models.URLField()),
            ],
        ),
    ]
