# Generated by Django 3.0.1 on 2020-02-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articleId',
        ),
        migrations.RemoveField(
            model_name='article',
            name='articleLink',
        ),
        migrations.RemoveField(
            model_name='article',
            name='articlePicture',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='datePosted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
