# Generated by Django 3.0.1 on 2020-03-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 12, 14, 322253), max_length=255, primary_key=True, serialize=False),
        ),
    ]
