# Generated by Django 3.0.1 on 2020-02-25 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200225_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 9, 1, 51, 984159), max_length=255, primary_key=True, serialize=False),
        ),
    ]
