# Generated by Django 3.0.1 on 2020-04-01 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200401_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 40, 28, 865897), max_length=255, primary_key=True, serialize=False),
        ),
    ]
