# Generated by Django 3.0.1 on 2020-02-25 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200225_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 9, 59, 52, 75729), max_length=255, primary_key=True, serialize=False),
        ),
    ]
