# Generated by Django 3.0.1 on 2020-02-25 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200225_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 10, 11, 47, 9619), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
