# Generated by Django 3.0.1 on 2020-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200225_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default='wewewew', max_length=255, primary_key=True, serialize=False),
        ),
    ]
