# Generated by Django 3.0.1 on 2020-02-25 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200225_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 18, 19, 745467), max_length=255, primary_key=True, serialize=False),
        ),
    ]
