# Generated by Django 3.0.1 on 2020-04-02 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200402_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 13, 10, 34, 615825), max_length=255, primary_key=True, serialize=False),
        ),
    ]
