# Generated by Django 3.0.1 on 2020-03-08 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20200225_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 3, 8, 14, 37, 27, 95336), max_length=255, primary_key=True, serialize=False),
        ),
    ]
