# Generated by Django 3.0.1 on 2020-03-21 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200308_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 507272), max_length=255, primary_key=True, serialize=False),
        ),
    ]
