# Generated by Django 3.0.1 on 2020-04-06 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20200406_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 4, 6, 17, 15, 27, 835043), max_length=255, primary_key=True, serialize=False),
        ),
    ]
