# Generated by Django 3.0.5 on 2020-04-08 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20200408_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 4, 8, 10, 40, 58, 101298), max_length=255, primary_key=True, serialize=False),
        ),
    ]
