# Generated by Django 3.0.1 on 2020-03-22 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20200322_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 535315), max_length=255, primary_key=True, serialize=False),
        ),
    ]
