# Generated by Django 3.0.5 on 2020-04-08 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20200408_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 4, 8, 10, 46, 49, 149310), max_length=255, primary_key=True, serialize=False),
        ),
    ]
