# Generated by Django 3.0.1 on 2020-03-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20200322_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 20, 13, 30, 557771), max_length=255, primary_key=True, serialize=False),
        ),
    ]
