dist: bionic
language: python

python:
  - '3.8'

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python manage.py test
  - python manage.py collectstatic --no-input

deploy:
  provider: gae
  skip_cleanup: true
  key_file: gae.json
  project: career-track
  on:
    branch: production
