# Generated by Django 3.0.5 on 2020-12-20 12:35

import app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201220_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous', max_length=50)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to=app.models.article_images_folder)),
                ('author_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to=app.models.article_images_folder)),
                ('article_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('read_time', models.DurationField(help_text='<b><em>In seconds e.g. enter 60 for 1 minute</em></b>')),
                ('bait', models.TextField(blank=True, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('claps', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_on'],
            },
        ),
    ]
