# Generated by Django 3.0.1 on 2020-03-08 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775181), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775224), max_length=255)),
                ('description', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775253), max_length=255)),
                ('university', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775279), max_length=255)),
                ('college', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775305), max_length=255)),
                ('duration', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775329), max_length=255)),
                ('essential', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775352), max_length=255)),
                ('relevant', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775375), max_length=255)),
                ('desirable', models.CharField(default=datetime.datetime(2020, 3, 8, 15, 15, 52, 775399), max_length=255)),
            ],
        ),
    ]
