# Generated by Django 3.0.1 on 2020-03-28 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('name', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703303), max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703352), max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703790), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703827), max_length=255)),
                ('description', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703856), max_length=255)),
                ('university', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703882), max_length=255)),
                ('college', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703907), max_length=255)),
                ('duration', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703931), max_length=255)),
                ('essential', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703955), max_length=255)),
                ('relevant', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 703979), max_length=255)),
                ('desirable', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 704003), max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OLevelConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.CharField(default='True', max_length=255)),
                ('maximum_grade', models.IntegerField(default=6)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.UceSubjects')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('essential', 'essential'), ('relevant', 'relevant'), ('desirable', 'desirable')], max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.UaceSubjects')),
            ],
        ),
        migrations.CreateModel(
            name='CourseConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essentials', models.IntegerField(choices=[(1, 'One Essential'), (2, 'Two Essentials'), (3, 'One or two essentials')], default=2)),
                ('relevant', models.IntegerField(default=2)),
                ('desirable_state', models.IntegerField(choices=[(1, 'Only one mandatory desirable'), (2, 'Depends on essential and relevant subjects')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Careers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='ALevelConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.CharField(default='True', max_length=255)),
                ('minimum_grade', models.IntegerField(default=2)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.UaceSubjects')),
            ],
        ),
    ]
