# Generated by Django 3.0.1 on 2020-03-21 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 509968), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510090), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510036), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desirable',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510205), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510128), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='essential',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510153), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510007), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='relevant',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510181), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 14, 41, 45, 510063), max_length=255),
        ),
        migrations.CreateModel(
            name='CourseConstraints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_essential', models.IntegerField(default=2)),
                ('no_of_relevant', models.IntegerField(default=1)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
            ],
        ),
    ]
