# Generated by Django 3.0.1 on 2020-03-28 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200328_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 530870), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 530811), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531290), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531436), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531358), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531461), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531328), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531486), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 11, 33, 531408), max_length=255),
        ),
    ]
