# Generated by Django 3.0.5 on 2020-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200409_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucesubjects',
            name='category',
            field=models.CharField(choices=[('Compulsory', 'Compulsory Subject'), ('Elective', 'Elective Subject')], default='Elective', max_length=15),
        ),
    ]
