# Generated by Django 3.0.1 on 2020-03-28 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200328_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955450), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955390), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='desirable_state',
            field=models.CharField(choices=[(1, 'Only one mandatory desirable'), (2, 'Depends on essential and relevant subjects')], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='essentials',
            field=models.CharField(choices=[(1, 'One Essential'), (2, 'Two Essentials'), (3, 'One or two essentials')], default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='relevant',
            field=models.CharField(default=2, max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955865), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955985), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955932), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 956009), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955902), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 956033), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 13, 17, 38, 955960), max_length=255),
        ),
    ]
