# Generated by Django 3.0.1 on 2020-03-22 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200322_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112265), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112390), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112339), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desirable',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112491), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112415), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='essential',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112439), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112309), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='relevant',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112467), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 17, 24, 44, 112366), max_length=255),
        ),
    ]
