# Generated by Django 3.0.1 on 2020-03-22 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200322_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('name', models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904424), max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904469), max_length=255)),
                ('courses', models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904499), max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904852), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904966), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904916), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desirable',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 905073), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904994), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='essential',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 905019), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904888), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='relevant',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 905049), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 40, 5, 904942), max_length=255),
        ),
        migrations.CreateModel(
            name='CareerCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Careers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
            ],
        ),
    ]
