# Generated by Django 3.0.1 on 2020-03-28 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200328_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alevelconstraints',
            name='mandatory',
        ),
        migrations.AddField(
            model_name='courseconstraints',
            name='a_level_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconstraints',
            name='all_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconstraints',
            name='o_level_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseconstraints',
            name='subject_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursesubjects',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 726415), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 726233), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727602), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727896), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727766), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727959), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727695), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 728019), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 28, 18, 26, 5, 727833), max_length=255),
        ),
    ]
