# Generated by Django 3.0.1 on 2020-03-22 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200322_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='courses',
        ),
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537237), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537195), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537581), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537695), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537644), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='desirable',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537800), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537719), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='essential',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537743), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537616), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='relevant',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537772), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 537670), max_length=255),
        ),
    ]
