# Generated by Django 3.0.1 on 2020-03-29 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200329_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 346522), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 346417), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='a_level_constraint',
            field=models.CharField(default='False', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='all_subjects',
            field=models.CharField(default='False', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='o_level_constraint',
            field=models.CharField(default='False', max_length=255),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='subject_constraint',
            field=models.CharField(default='False', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347152), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347297), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347232), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347329), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347196), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347360), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 12, 26, 57, 347265), max_length=255),
        ),
        migrations.AlterField(
            model_name='coursesubjects',
            name='compulsory_state',
            field=models.CharField(default='False', max_length=255),
        ),
    ]
