# Generated by Django 3.0.1 on 2020-04-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200401_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 801622), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 801585), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802019), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802135), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802081), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802160), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802054), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802183), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 16, 802107), max_length=255),
        ),
    ]
