# Generated by Django 3.0.1 on 2020-04-02 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20200402_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 562637), max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 562582), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='a_level_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='all_subjects',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='o_level_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='subject_constraint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563102), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563221), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563170), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563246), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563140), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563271), max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 6, 32, 563196), max_length=255),
        ),
        migrations.AlterField(
            model_name='coursesubjects',
            name='compulsory_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='olevelconstraints',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
