# Generated by Django 3.0.1 on 2020-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20200402_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.CharField(default='Provide career description', max_length=255),
        ),
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(default='Provide career name', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='code',
            field=models.CharField(default='Provide course code', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.CharField(default='Provide college', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='Provide course description', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(default='Provide course name', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.CharField(default='Day', max_length=255),
        ),
        migrations.AlterField(
            model_name='courses',
            name='university',
            field=models.CharField(default='Provide university', max_length=255),
        ),
    ]
