# Generated by Django 3.0.1 on 2020-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20200402_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubjects',
            name='category',
            field=models.CharField(choices=[('essential', 'essential'), ('relevant', 'relevant'), ('desirable', 'desirable')], default='essential', max_length=15),
        ),
    ]
