# Generated by Django 3.0.1 on 2020-04-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200402_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconstraints',
            name='essentials',
            field=models.CharField(choices=[(1, 'Has one essential'), (2, 'Has two essentials'), (3, 'Can have one or two essentials')], default=2, max_length=15),
        ),
    ]
