# Generated by Django 3.0.1 on 2020-04-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20200402_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconstraints',
            name='essentials',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2),
        ),
    ]
