# Generated by Django 3.0.1 on 2020-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20200402_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconstraints',
            name='desirable_state',
            field=models.IntegerField(choices=[(1, 'One Mandatory'), (2, 'Depends')], default=1),
        ),
        migrations.AlterField(
            model_name='courseconstraints',
            name='essentials',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'One or Two')], default=2),
        ),
    ]
