# Generated by Django 3.0.1 on 2020-04-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20200405_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutOffPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2019)),
                ('points', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government')], default='Private', max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Courses')),
            ],
        ),
    ]
