# Generated by Django 3.0.1 on 2020-04-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_cutoffpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffpoints',
            name='type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=15),
        ),
    ]
