# Generated by Django 3.0.1 on 2020-02-25 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UaceSubjects',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 2, 25, 18, 23, 41, 540715), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UceSubjects',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 2, 25, 18, 23, 41, 541937), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
