# Generated by Django 3.0.1 on 2020-03-28 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UaceSubjects',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 701015), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='optional', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UceSubjects',
            fields=[
                ('code', models.CharField(default=datetime.datetime(2020, 3, 28, 12, 59, 22, 701496), max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
