# Generated by Django 3.0.1 on 2020-04-01 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200328_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uacesubjects',
            options={'verbose_name': 'Uace Subjects', 'verbose_name_plural': 'Uace Subjects'},
        ),
        migrations.AlterModelOptions(
            name='ucesubjects',
            options={'verbose_name': 'Uce Subjects', 'verbose_name_plural': 'Uce Subjects'},
        ),
        migrations.AddField(
            model_name='uacesubjects',
            name='abbr',
            field=models.CharField(default='<', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 39, 6, 688507), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 39, 6, 689144), max_length=255, primary_key=True, serialize=False),
        ),
    ]
