# Generated by Django 3.0.1 on 2020-02-25 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200225_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucesubjects',
            name='category',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 13, 17, 148108), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 13, 17, 148497), max_length=255, primary_key=True, serialize=False),
        ),
    ]
