# Generated by Django 3.0.1 on 2020-02-25 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200225_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucesubjects',
            name='category',
        ),
        migrations.AddField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 16, 58, 976488), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 16, 58, 976932), max_length=255, primary_key=True, serialize=False),
        ),
    ]
