# Generated by Django 3.0.1 on 2020-02-25 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20200225_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(default='compulsory', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 18, 19, 746181), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 18, 19, 746612), max_length=255, primary_key=True, serialize=False),
        ),
    ]
