# Generated by Django 3.0.1 on 2020-04-01 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20200401_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('ART', 'Art'), ('SUBSIDIARY', 'Subsidiary')], default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 1, 380069), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 1, 14, 49, 1, 380611), max_length=255, primary_key=True, serialize=False),
        ),
    ]
