# Generated by Django 3.0.1 on 2020-04-02 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20200401_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Art', 'Art'), ('Subsidiary', 'Subsidiary')], default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 4, 37, 391585), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 12, 4, 37, 392140), max_length=255, primary_key=True, serialize=False),
        ),
    ]
