# Generated by Django 3.0.1 on 2020-02-25 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20200225_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 49, 26, 369735), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 2, 25, 19, 49, 26, 370167), max_length=255, primary_key=True, serialize=False),
        ),
    ]
