# Generated by Django 3.0.1 on 2020-03-21 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20200321_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 19, 25, 48, 906403), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 21, 19, 25, 48, 906840), max_length=255, primary_key=True, serialize=False),
        ),
    ]
