# Generated by Django 3.0.1 on 2020-04-02 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20200402_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 13, 8, 40, 847849), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 13, 8, 40, 848416), max_length=255, primary_key=True, serialize=False),
        ),
    ]
