# Generated by Django 3.0.1 on 2020-04-02 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_auto_20200402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(choices=[('Science', 'Science Subject'), ('Art', 'Art Subject'), ('Subsidiary', 'Subsidiary Subject')], default='Art', max_length=15),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 13, 27, 19, 930395), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 4, 2, 13, 27, 19, 932532), max_length=255, primary_key=True, serialize=False),
        ),
    ]
