# Generated by Django 3.0.1 on 2020-03-22 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0016_auto_20200322_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 536037), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 22, 18, 46, 36, 536476), max_length=255, primary_key=True, serialize=False),
        ),
    ]
