# Generated by Django 3.0.1 on 2020-04-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_auto_20200402_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default='Subject code begin with UACE_', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default='Subject code begin with UCE_', max_length=255, primary_key=True, serialize=False),
        ),
    ]
