# Generated by Django 3.0.1 on 2020-03-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_auto_20200322_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(default='optional', max_length=255),
        ),
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 20, 13, 30, 558463), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 20, 13, 30, 558898), max_length=255, primary_key=True, serialize=False),
        ),
    ]
