# Generated by Django 3.0.1 on 2020-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_auto_20200402_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='category',
            field=models.CharField(choices=[('Science', 'Science Subject'), ('Art', 'Art Subject'), ('Subsidiary', 'Subsidiary Subject'), ('Category', 'Category placeholder')], default='Art', max_length=15),
        ),
    ]
