# Generated by Django 3.0.1 on 2020-03-26 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_auto_20200326_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 20, 38, 0, 266586), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ucesubjects',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 3, 26, 20, 38, 0, 267037), max_length=255, primary_key=True, serialize=False),
        ),
    ]
